import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import localFont from "next/font/local";

const NHaasFont = localFont({
  src: [
    {
      path: "../components/assets/fonts/NHhaas-thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../components/assets/fonts/NeueHaasGroteskDisplay-25XThin-Web.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../components/assets/fonts/NHhaas-light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../components/assets/fonts/NHaasGroteskDSStd-55Rg.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../components/assets/fonts/NHhaas-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../components/assets/fonts/NHaasGroteskTXStd-75Bd.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-nhaas",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NHaasFont.className} antialiased`}
      >
        <div>

        <Header />
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
